const data = {
  products: [
    {
      id: 1,
      name: "Nike Formals Shirt",
      category: "Shirt",
      image: "https://amazona.webacademy.pro/images/p1.jpg",
      price: "780",
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      id: 2,
      name: "Addidas Fit Shirt",
      category: "Shirt",
      image: "https://amazona.webacademy.pro/images/p2.jpg",
      price: "670",
      brand: "Addidas",
      rating: 4.2,
      numReviews: 10,
      description: "High quality product",
    },
    {
      id: 3,
      name: "H&M Formals shirts",
      category: "Shirt",
      image: "https://amazona.webacademy.pro/images/p3.jpg",
      price: "1080",
      brand: "H&M",
      rating: 4.7,
      numReviews: 10,
      description: "High quality product",
    },
    {
      id: 4,
      name: "H&M Formals Pant",
      category: "Pant",
      image: "https://amazona.webacademy.pro/images/p4.jpg",
      price: "1680",
      brand: "H&M",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      id: 5,
      name: "H&M Slim Pants",
      category: "Pant",
      image: "https://amazona.webacademy.pro/images/p5.jpg",
      price: "780",
      brand: "H&M",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      id: 6,
      name: "Lee Formals ",
      category: "Pant",
      image: "https://amazona.webacademy.pro/images/p6.jpg",
      price: "1780",
      brand: "Lee",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
  ],
};

export default data;
